import os.path

DIRPATH = os.path.dirname(os.path.realpath(__file__))

SAMTOOLS = "/Users/pcaso/bin/samtools"

MAIN_CHROM_LIST   = ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","X","Y","M"]

FIELDLIST_VCFQC = {}
FIELDLIST_VCFQC['QCBOARD'] = ['NOSAMPLE']
FIELDLIST_VCFQC['TITV'] = ['TITV','TI','TV']
FIELDLIST_VCFQC['HETHOM'] = ['HETHOM','HET','HOMALT','HOMREF','HETALT','MISS']
FIELDLIST_VCFQC['HETHOM_INDEL'] = ['HETHOM','HET','HOMALT','HOMREF','HETALT','MISS']
FIELDLIST_VCFQC['VARTYPE'] = ['SNV','MNV','INDEL','INS','DEL','MIXED']
FIELDLIST_VCFQC['SUBSTITUTION'] = ['C_A','C_G','C_T','T_A','T_C','T_G']
FIELDLIST_VCFQC['CHROM'] = MAIN_CHROM_LIST
FIELDLIST_VCFQC['CHROM_INDEL'] = MAIN_CHROM_LIST

VCF_HEADCOL = ['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT']

